# Generated by Django 3.2.5 on 2021-07-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
