# Generated by Django 3.2.5 on 2021-07-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0002_timeline_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='date',
            field=models.DateField(),
        ),
    ]
