# Generated by Django 3.2.5 on 2021-07-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_alter_timelineevent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
