# Generated by Django 3.2.5 on 2021-08-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0004_auto_20210729_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeline',
            name='button_text',
            field=models.CharField(default='Back to my homepage', max_length=50),
        ),
        migrations.AddField(
            model_name='timeline',
            name='button_url',
            field=models.URLField(default='#'),
        ),
    ]
