# Generated by Django 3.2.5 on 2021-08-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0005_auto_20210802_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='button_url',
            field=models.URLField(default='/'),
        ),
    ]
