# Generated by Django 3.2.5 on 2021-08-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0006_alter_timeline_button_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='button_text',
            field=models.CharField(default='Back', max_length=50),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='button_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
